---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    folders:
    - path: /Applications
    - path: ~
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Mark Yen
    git_user_email: mark@uber.com
  - role: brew_package
    package_name: git-extras
  - role: brew_package
    package_name: arcanist
  - role: brew_package
    package_name: tmux
  - role: maximum_awesome
  ## languages
  - role: brew_package
    package_name: nvm
  - role: npm_package
    package_name: jshint
  - role: npm_package
    package_name: grunt-cli
  - role: npm_package
    package_name: bower
  - role: npm_package
    package_name: coffee-script
  - role: brew_package
    package_name: python
  - role: brew_package
    package_name: python3
  - role: pip_package
    package_name: virtualenv
  - role: pip_package
    package_name: virtualenvwrapper
  - role: brew_package
    package_name: numpy
  - role: brew_package
    package_name: scipy
  - role: pip_package
    package_name: ipython
  - role: pip_package
    package_name: matplotlib
  - role: pip_package
    package_name: pandas
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: android-sdk
  - role: brew_package
    package_name: scala
  - role: brew_package
    package_name: sbt
  - role: brew_package
    package_name: go
  - role: brew_package
    package_name: rust
  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: redis
  - role: brew_package
    package_name: elasticsearch

  # gui
  ## deployment
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: virtualbox
  ## browsers
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: firefox
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    tap: caskroom/versions
    package_name: sublime-text3
  - role: cask_package
    package_name: intellij-idea
  - role: cask_package
    package_name: lighttable
  ## messaging
  - role: cask_package
    package_name: hipchat
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: airmail
  ## file sharing
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: evernote
  - role: cask_package
    package_name: notational-velocity
  ## tooling
  - role: cask_package
    package_name: the-unarchiver
  - role: cask_package
    package_name: quicksilver
  - role: cask_package
    package_name: bettertouchtool
  - role: cask_package
    package_name: flux
  - role: cask_package
    package_name: caffeine
  - role: cask_package
    package_name: zooom
  ## entertainment
  - role: cask_package
    package_name: google-hangouts
  - role: cask_package
    package_name: chromecast
  - role: cask_package
    package_name: rdio
